# Generated by Django 3.2 on 2023-02-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='location',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='medicinecategory',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='medicinename',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='symptoms',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
